=== robbik/nucleus8583/nucleus8583-oim/src/main/resources/META-INF/nucleus8583/nucleus8583-oim.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.nucleus8583.org/schema/nucleus8583-oim"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.nucleus8583.org/schema/nucleus8583-oim"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">

    <xsd:simpleType name="fieldNo">
        <xsd:restriction base="xsd:unsignedInt">
            <xsd:minInclusive value="0" />
            <xsd:maxInclusive value="192" />
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="length">
        <xsd:restriction base="xsd:int">
            <xsd:minInclusive value="1" />
            <xsd:maxInclusive value="2000000000" />
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="mode">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="text" />
            <xsd:enumeration value="binary" />
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="access">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="FIELD" />
            <xsd:enumeration value="PROPERTY" />
            <xsd:enumeration value="VIRTUAL" />
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:complexType name="simple-type">
        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="class" type="xsd:string" use="required" />

        <xsd:attribute name="description" type="xsd:string" use="optional" default="" />
        
        <xsd:anyAttribute namespace="##any" processContents="lax" />
    </xsd:complexType>

    <xsd:complexType name="complex-type">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="expression" type="expression" />
            <xsd:element name="basic" type="basic" />
            <xsd:element name="skip" type="skip" />
            <xsd:element name="pad" type="pad" />
            <xsd:element name="record" type="record" />
            <xsd:element name="list" type="list" />
            <xsd:element name="list-count" type="list-count" />
        </xsd:choice>

        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="class" type="xsd:string" use="required" />
        <xsd:attribute name="access" type="access" use="required" />
    </xsd:complexType>

    <xsd:complexType name="expression">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="language" type="xsd:string" use="required" />
		        <xsd:attribute name="type" type="xsd:string" use="required" />
		        
		        <xsd:anyAttribute namespace="##any" processContents="lax" />
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="basic">
        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="type" type="xsd:string" use="required" />
        
        <xsd:anyAttribute namespace="##any" processContents="lax" />
    </xsd:complexType>

    <xsd:complexType name="skip">
        <xsd:attribute name="length" type="length" use="required" />
    </xsd:complexType>

    <xsd:complexType name="pad">
        <xsd:attribute name="padWith" type="xsd:string" use="required" />
        <xsd:attribute name="mode" type="mode" use="required" />
    </xsd:complexType>

    <xsd:complexType name="record">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="expression" type="expression" />
            <xsd:element name="basic" type="basic" />
            <xsd:element name="skip" type="skip" />
            <xsd:element name="pad" type="pad" />
            <xsd:element name="record" type="record" />
            <xsd:element name="list" type="list" />
            <xsd:element name="list-count" type="list-count" />
        </xsd:choice>

        <xsd:attribute name="mode" type="mode" use="required" />
    </xsd:complexType>

    <xsd:complexType name="list">
        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="type" type="xsd:string" use="required" />

        <xsd:attribute name="partial" type="xsd:boolean" use="optional" default="false" />
        <xsd:attribute name="capacity" type="length" use="optional" default="2000000000" />
    </xsd:complexType>

    <xsd:complexType name="list-count">
        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="type" type="xsd:string" use="required" />
        
        <xsd:anyAttribute namespace="##any" processContents="lax" />
    </xsd:complexType>

    <xsd:complexType name="root-expression">
        <xsd:complexContent>
            <xsd:extension base="expression">
                <xsd:attribute name="no" type="fieldNo" use="required" />
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="root-basic">
        <xsd:complexContent>
            <xsd:extension base="basic">
                <xsd:attribute name="no" type="fieldNo" use="required" />
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="root-skip">
        <xsd:complexContent>
            <xsd:extension base="skip">
                <xsd:attribute name="no" type="fieldNo" use="required" />
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="root-pad">
        <xsd:complexContent>
            <xsd:extension base="pad">
                <xsd:attribute name="no" type="fieldNo" use="required" />
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="root-record">
        <xsd:complexContent>
            <xsd:extension base="record">
                <xsd:attribute name="no" type="fieldNo" use="required" />
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="root-list">
        <xsd:complexContent>
            <xsd:extension base="list">
                <xsd:attribute name="no" type="fieldNo" use="required" />
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="root-list-count">
        <xsd:complexContent>
            <xsd:extension base="list-count">
                <xsd:attribute name="no" type="fieldNo" use="required" />
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="message">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="expression" type="root-expression" />
            <xsd:element name="basic" type="root-basic" />
            <xsd:element name="skip" type="root-skip" />
            <xsd:element name="pad" type="root-pad" />
            <xsd:element name="record" type="root-record" />
            <xsd:element name="list" type="root-list" />
            <xsd:element name="list-count" type="root-list-count" />
        </xsd:choice>

        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="class" type="xsd:string" use="required" />
        <xsd:attribute name="access" type="access" use="required" />
    </xsd:complexType>

    <xsd:complexType name="import">
        <xsd:attribute name="url" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="require">
        <xsd:attribute name="url" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:element name="nucleus8583-oim">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:choice minOccurs="0" maxOccurs="unbounded">
                    <xsd:element name="simple-type" type="simple-type" />
                    <xsd:element name="complex-type" type="complex-type" />
                    <xsd:element name="message" type="message" />
                    <xsd:element name="import" type="import" />
                    <xsd:element name="require" type="require" />
                </xsd:choice>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== robbik/nucleus8583/nucleus8583-oim/src/test/resources/META-INF/oim-sample.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<nucleus8583-oim xmlns="http://www.nucleus8583.org/schema/nucleus8583-oim"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.nucleus8583.org/schema/nucleus8583-oim 
                                     http://www.nucleus8583.org/schema/nucleus8583-oim.xsd">
    
    <complex-type name="details" class="java.util.HashMap" access="VIRTUAL">
        <basic name="z" type="text" length="8" />
    </complex-type>
    
	<message name="msg1" class="java.util.HashMap" access="VIRTUAL">
		<expression no="0" type="text" language="literal">0110</expression>
		<basic no="2" name="cardNumber" type="text" />
		<basic no="7" name="transmissionDateTime" type="dateTime" pattern="MMddHHmmss" />
		<basic no="11" name="stan" type="int" />
		<basic no="12" name="transactionTime" type="dateTime" pattern="HHmmss" />
		<basic no="13" name="transactionDate" type="dateTime" pattern="MMdd" />
        
		<record no="29" mode="text">
			<pad padWith="C" mode="text" />
			<basic name="charge" type="signedNumeric" length="8" precision="2" signFirst="false" />
		</record>
        
		<basic no="37" name="rrn" type="text" />
		<basic no="39" name="responseCode" type="text" />
		
        <record no="48" mode="text">
            <list-count name="details" type="int" length="2" />
            <list name="details" type="details" />
        </record>
	</message>
    
    <message name="msg1_rev" class="java.util.HashMap" access="VIRTUAL">
        <basic no="2" name="cardNumber" type="text" />
        <basic no="7" name="transmissionDateTime" type="dateTime" pattern="MMddHHmmss" />
        <basic no="11" name="stan" type="int" alignment="right" padWith="0" />
        <basic no="12" name="transactionTime" type="dateTime" pattern="HHmmss" />
        <basic no="13" name="transactionDate" type="dateTime" pattern="MMdd" />
        
        <record no="29" mode="text">
            <skip length="1" />
            <basic name="charge" type="signedNumeric" length="8" precision="2" signFirst="false" />
        </record>
        
        <basic no="37" name="rrn" type="text" />
        <basic no="39" name="responseCode" type="text" />
        
        <record no="48" mode="text">
            <list-count name="details" type="int" length="2" />
            <list name="details" type="details" />
        </record>
    </message>
</nucleus8583-oim>
